services:
  - type: web
    name: kaeru-log
    env: node
    plan: free
    repo: https://github.com/Yosshy-123/KAeRU-Log.git
    branch: main
    region: oregon
    autoDeploy: true
    envVars:
      REDIS_URL: ""
      ADMIN_PASS: ""
      SECRET_KEY: ""
      WORKER_SECRET: ""
      NODE_ENV: "production"

  - type: pserv
    name: kaeru-log-redis
    env: redis
    plan: starter-redis
    maxmemoryPolicy: noeviction
