services:
  - type: web
    name: kaeru-log
    env: node
    plan: free
    repo: https://github.com/Yosshy-123/KAeRU-Log.git
    branch: main
    region: oregon
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        value: ""
      - key: ADMIN_PASS
        value: ""
      - key: SECRET_KEY
        value: ""
      - key: WORKER_SECRET
        value: ""
      - key: NODE_ENV
        value: "production"

  - type: pserv
    name: kaeru-log-redis
    env: redis
    plan: starter-redis
