services:
  - type: web
    name: kaeru-log
    env: node
    plan: free
    repo: https://github.com/Yosshy-123/KAeRU-Log.git
    branch: main
    region: oregon
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: REDIS_URL
        value: ""
      - key: ADMIN_PASS
        value: ""

  - type: keyvalue
    name: kaeru-log-redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []
